# Generated by Django 5.1.7 on 2025-03-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfdocument',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
