# Generated by Django 5.1.7 on 2025-03-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0002_rename_uploaded_at_pdfdocument_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='name',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='language',
            field=models.CharField(default='spa', max_length=3),
        ),
    ]
