# Generated by Django 5.1.7 on 2025-03-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0003_remove_pdfdocument_name_pdfdocument_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='language',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
